### PR TITLE
Fix text box

### PR DESCRIPTION
**Pull request by darrellp**
Still learning on this pull request stuff.  I made the change on a separate branch and now it's telling me "Can't automatically merge" in ominous red above but I think this is what I'm supposed to do.  Anyway, fixing the textbox cursor positioning here.  I noticed somebody else was bringing that up and I need it in my little editor.  Made a semi-cosmetic change in listbox.cpp but the real stuff is in the theme.  I tested all the cases of keyboard editing that I could see in TextBox.ProcessKeyboard and it all worked.  Hope this seems right to you.  Thanks!

### CODE REVIEW

**Comment by SadConsole** [comment]
So, I don't think the problem is a **real** problem. I recently pushed an update for the 8.0 release to master, which includes a big refactor of themes. This is probably where your conflict is.

Give me a second and I'll create a different branch for you to target

**Comment by darrellp** [comment]
So how should I have prevented this from being any sort of problem at all?  Should I have pulled the main branch just before my checkin and then somehow "merged" any changes there over to my FixTextBox branch?  Sorry to appear so ignorant.  I haven't really used Git in a team context.  Just make changes, commit, make changes, commit to my own little projects.  I really feel pretty dumb in the team context.

**Comment by darrellp** [comment]
I see the problem - you renamed "control" to "textbox" in the theme.  Simple enough.  I'm not quite sure what I need to do to fix it.  Sorry to nag.  I'll sit and wait patiently now for some sage advice.

**Comment by SadConsole** [comment]
Yes but technically you wouldn't have been working with what is shipped, you would be working on the next major release. If this fix addresses a problem in the current release, it's better to do it in the release branch for that version. I've just been in the middle of trying to revamp my branches to make this stuff better :)

**Comment by SadConsole** [comment]
Use branch `develop-7.3`

**Comment by SadConsole** [comment]
You have to open a new PR between your branch and the `release-7.3`

**Pull request closed without merging**
