### PR TITLE
Fix text box

### PR DESCRIPTION
**Pull request by darrellp**
Third time's a charm - I hope.  Fixed TextBox cursor positioning so TextBox works mostly as expected.

### CODE REVIEW

**Comment by SadConsole** [comment]
thats looking better 👍 

few things I noticed

1. You are using TAB characters for indentation, but the source uses spaces.
2. Because of this, the file `src/SadConsole.Shared/Surfaces/SurfaceBase.cs` actually has a bad edit in it, it just re-indented the property, but there is no code change. You should revert this file. If you have the git command line, you can easily do this in your source but getting back the original file. `git checkout -- <path to file>` will do it. Then you can commit the change and push to your branch

**Comment by darrellp** [comment]
Oops.  I'll fix that in my options.  Thanks for your patience!

**Comment by SadConsole** [comment]
Thank you for your help!

**Comment by SadConsole** [comment]
If you need any help, feel free to join in the discord and ask questions. There are git novice and experts there 😄

**Pull request merged**
