### PR TITLE
Update Content system with async methods

### PR DESCRIPTION
**Pull request by erictuvesson**
While I wrote this I noticed that the Serializer class is only used once in the project (not anymore), I didn't want to remove it as it is probably used in some games?

I am not sure if this code is really used, is that something we can remove?
```csharp
Settings.LoadingEmbeddedFont = true;
Global.SerializerPathHint = "";
```

_(the LoadFontAsync method is probably a bad idea...)_

### CODE REVIEW

**Comment by SadConsole** [comment]
Thanks for the PR 😄 

There are two things the serializer class handles two things:

01. Passing things through the GZIP compressor if needed.
02. Handling the MonoGame restrictions around loading streams.

    You can't use the `File` namespace to load resources on some other platforms, like android or ios (i think) so MonoGame provides the `Microsoft.Xna.Framework.TitleContainer.OpenStream` helper for that. I don't think I ever implemented that on `Save` just on `Load`, but it should be there for `Save` too.

**Comment by Thraka** [comment]
@erictuvesson sorry for the delay on this. i haven't had the time to really test and integrate this to make sure it's all good. I'm still here and watching though.

**Comment by erictuvesson** [comment]
_Just to add some context, we talked about merging this to v9 instead._

**Comment by SadConsole** [comment]
Closing this for now @erictuvesson time to start working on v9 redesign 😄

**Pull request closed without merging**
