### PR TITLE
Update all using statements

### PR DESCRIPTION
**Pull request by erictuvesson**
Hi,

Sorry about all the changes there are a lot. 😄 

In short all the things I have done here is add a preprocessor if-statements on all the Xna includes and some minor style changes.

I don't see why "MONOGAME" is added as a preprocessor define in some projects as it doesn't seem to be used anywhere useful.

### CODE REVIEW

**Comment by SadConsole** [comment]
Wow. 

I had a lot of that preprocessor and stuff like MyMathHelper to avoid conflicts when I supported both monogame and sfml frameworks. 

This is a lot to look at and validate. So the main point of this is not to add veldrid right away at this point, but to clean up and prep for a multiframework system?

**Comment by SadConsole** [comment]
Also, I wouldn't get too crazy with implementing something like veldrid. I've also been investigating how to use [OpenWheels](https://github.com/Jjagg/OpenWheels) (which can target monogame or veldrid) but it's very very new. 

I just dont want you to do a ton of work and then we end up going a different way or something.

**Comment by erictuvesson** [comment]
I started by adding Veldrid, but doing that would just make it hard for you to look at. So I am taking it step by step so the code is easier to manage for adding some new back-end.

As I feel this is a framework that can run on it's own I don't want to add some other high-end library, so I was thinking of just adding it's own rendering system that is using Veldrid.

**Comment by SadConsole** [comment]
Yes, originally that is what I was thinking with this too. Something that is its own thing based on veldrid. However, that is a whole other level of game programming that I've not really delved into 😄 much. So OpenWheels is something I can easily prototype with. Nothing is set in stone though. This is all playing around.

Additionally I have some other things I want to work on with sadconsole+veldrid. I'm thinking:

1. C# 8 and .NET Standard 2.1 - This pulls out .NET Framework, and I'm fine with that
2. Redesigning for multithreading. I think it would be nice to pull out update/draw into their own threads.
3. Multi-window system so you can display more than one thing in a window

I'm thinking that in reality this will all be a SadConsole 9.0 thing. So your commits that clean up code for 8.0 are really welcome 😄

**Pull request merged**
